"""
Django settings for cozastore project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.conf import settings
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

load_dotenv()




# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'gp$735r^9wg#5_+))-cx#*-1mjp=5wx=7-0k8j(#2vt0(cuv&z'
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret-for-local")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',  



    "customer",
    "seller",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cozastore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'django.template.context_processors.i18n',

            ],
        },
    },
]

WSGI_APPLICATION = 'cozastore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR + '/db.sqlite3',
#     }
# }

# DATABASES = {
#     "default": dj_database_url.config(
#         default="sqlite:///db.sqlite3",
#         conn_max_age=600,
#         ssl_require=True
#     )
# }


# DATABASES = {
#     'default': dj_database_url.parse(
#         os.environ.get(
#             "DATABASE_URL",
#             "postgres://postgres:YOUR_PASSWORD@localhost:5432/cozastore_db"
#         )
#     )

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'cozastore_db',        # or 'postgres' if you're using default db
#         'USER': 'postgres',      # or 'postgres'
#         'PASSWORD': 'NewAdmin123!',  # exact password you set
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }



load_dotenv()

DATABASES = {
    "default": dj_database_url.parse(os.getenv("DATABASE_URL"))
}



STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"




# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")



if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATIC_URL = '/static/'


# send email

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "manavmshah2002@gmail.com"
EMAIL_HOST_PASSWORD = "esir nhhj bfiq ntrn"
# ===============================
# ⚡ STRIPE PAYMENT GATEWAY KEYS
# ===============================

STRIPE_PUBLIC_KEY = "pk_test_51SUZw1Hi23Wvk6eE2Bg17XynEa8e4NPlYUFhogCQw2Jkqqt48IDqhCAphOpb2ffnfm9ICJrlGcePMoQyi6eGJSKs00ZSrdafBN"
STRIPE_SECRET_KEY = "sk_test_51SUZw1Hi23Wvk6eEf8yYT3BmtoDdz1TjXs8UzcXNTQZ4HoHL0fkrTMnVaT9w1fJQLdNcYWW59cnzmoIpPQ2VDDps00P0ZhZ9bJ"