# Generated by Django 5.2.9 on 2025-12-02 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.BigIntegerField(unique=True)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Seller',
            },
        ),
        migrations.CreateModel(
            name='Seller_Authenticate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('auth_otp', models.CharField(max_length=30)),
                ('is_verify', models.BooleanField(default=False)),
                ('is_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('desc', models.TextField()),
                ('image', models.ImageField(default='images/sample.jpg', upload_to='images/product/')),
                ('in_stock', models.BooleanField(default=False)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
